"""Generate Sphinx RST documentation for MCP servers.

Since mcp-server/ uses a hyphen (not a valid Python package name),
Sphinx autodoc cannot import these modules. This script parses them
via AST and generates a manual RST page with extracted docstrings,
classes, and methods.

Usage:
	python docs/sphinx/generate_mcp_rst.py

Run this whenever mcp-server/ files are added or updated.
Output: docs/sphinx/api/mcp_servers.rst
"""

import ast
import re
from pathlib import Path
from typing import Dict, List, Optional


def extract_module_info(filepath: Path) -> Dict:
	"""Extract documentation info from an MCP server file via AST."""
	with open(filepath, encoding="utf-8") as f:
		source = f.read()

	tree = ast.parse(source)
	docstring = ast.get_docstring(tree) or ""

	# Parse structured sections from docstring
	sections = parse_docstring_sections(docstring)

	# Extract classes and their methods
	classes = []
	for node in ast.iter_child_nodes(tree):
		if isinstance(node, ast.ClassDef):
			class_doc = ast.get_docstring(node) or ""
			methods = []
			for item in node.body:
				if isinstance(item, ast.FunctionDef) and not item.name.startswith("_"):
					method_doc = ast.get_docstring(item) or ""
					# Build signature
					params = []
					for arg in item.args.args:
						if arg.arg != "self":
							hint = ""
							if arg.annotation:
								hint = ast.unparse(arg.annotation) if hasattr(ast, "unparse") else ""
							params.append(f"{arg.arg}: {hint}" if hint else arg.arg)
					ret = ""
					if item.returns:
						ret = ast.unparse(item.returns) if hasattr(ast, "unparse") else ""
					sig = f"{item.name}({', '.join(params)})"
					if ret:
						sig += f" -> {ret}"
					methods.append({
						"name": item.name,
						"signature": sig,
						"docstring": method_doc.split("\n")[0] if method_doc else "",
					})

			# Get base classes
			bases = []
			for base in node.bases:
				if hasattr(ast, "unparse"):
					bases.append(ast.unparse(base))

			classes.append({
				"name": node.name,
				"bases": bases,
				"docstring": class_doc,
				"methods": methods,
			})

	return {
		"filename": filepath.name,
		"title": sections.get("title", filepath.stem),
		"purpose": sections.get("purpose", ""),
		"architecture": sections.get("architecture", ""),
		"usage": sections.get("usage", ""),
		"models": sections.get("models_supported", ""),
		"parameters": sections.get("parameters", ""),
		"authentication": sections.get("authentication", ""),
		"classes": classes,
	}


def parse_docstring_sections(docstring: str) -> Dict[str, str]:
	"""Parse RST-style sections from MCP server docstrings."""
	if not docstring:
		return {}

	sections: Dict[str, str] = {}
	lines = docstring.strip().split("\n")

	# First line is the title
	if lines:
		sections["title"] = lines[0].strip()

	current_section: Optional[str] = None
	current_lines: List[str] = []

	for line in lines[1:]:
		stripped = line.strip()
		# Stop at Author line
		if stripped.startswith("Author:"):
			break
		# Detect section headers (e.g., "PURPOSE:", "ARCHITECTURE:")
		if (stripped.endswith(":")
				and stripped[:-1].replace(" ", "_").upper() == stripped[:-1].replace(" ", "_")
				and len(stripped) > 3):
			if current_section is not None:
				sections[current_section] = "\n".join(current_lines).strip()
			section_key = stripped[:-1].lower().replace(" ", "_")
			current_section = section_key
			current_lines = []
		elif stripped and all(c in "-=" for c in stripped):
			# Skip RST underlines
			continue
		elif current_section is not None:
			current_lines.append(line)

	if current_section is not None:
		sections[current_section] = "\n".join(current_lines).strip()

	return sections


def escape_rst(text: str) -> str:
	"""Escape characters that have special meaning in RST."""
	# Escape asterisks that aren't already in code/literal blocks
	text = re.sub(r'(?<!\*)\*(?!\*)', r'\*', text)
	return text


def generate_rst(mcp_dir: Path) -> str:
	"""Generate RST documentation for all MCP servers."""
	rst = []
	rst.append("MCP Servers")
	rst.append("=" * len("MCP Servers"))
	rst.append("")
	rst.append("Standalone JSON-RPC 2.0 servers for multi-provider LLM access.")
	rst.append("Each server implements the MCP protocol over stdin/stdout.")
	rst.append("")
	rst.append(".. note::")
	rst.append("")
	rst.append("   MCP servers live in ``mcp-server/`` (standalone scripts, not a Python package).")
	rst.append("   This documentation is generated by ``docs/generate_mcp_rst.py``.")
	rst.append("")

	# Collect and sort server files (base first, then alphabetical)
	server_files = sorted(mcp_dir.glob("*.py"))
	# Put base_mcp_server first, secure_logger last
	priority = {"base_mcp_server.py": 0, "secure_logger.py": 99}
	server_files.sort(key=lambda f: (priority.get(f.name, 1), f.name))

	for filepath in server_files:
		if filepath.name.startswith("test_") or filepath.name == "__init__.py":
			continue

		info = extract_module_info(filepath)

		# Section heading
		heading = info["title"]
		rst.append(heading)
		rst.append("-" * len(heading))
		rst.append("")
		rst.append(f"**File:** ``mcp-server/{info['filename']}``")
		rst.append("")

		if info["purpose"]:
			rst.append(escape_rst(info["purpose"]))
			rst.append("")

		# Authentication
		if info["authentication"]:
			rst.append("**Authentication:**")
			rst.append("")
			for line in info["authentication"].strip().split("\n"):
				stripped = line.strip()
				if stripped:
					rst.append(f"   {stripped}")
			rst.append("")

		# Models supported
		if info["models"]:
			rst.append("**Models:**")
			rst.append("")
			for line in info["models"].strip().split("\n"):
				stripped = line.strip()
				if stripped:
					if stripped.startswith("-"):
						rst.append(f"   {stripped}")
					else:
						rst.append(f"   - {stripped}")
			rst.append("")

		# Classes
		for cls in info["classes"]:
			cls_heading = cls["name"]
			if cls["bases"]:
				cls_heading += f"({', '.join(cls['bases'])})"
			rst.append(f".. class:: {cls_heading}")
			rst.append("")
			if cls["docstring"]:
				first_line = cls["docstring"].split("\n")[0].strip()
				if first_line:
					rst.append(f"   {escape_rst(first_line)}")
					rst.append("")

			# Methods
			for method in cls["methods"]:
				rst.append(f"   .. method:: {method['signature']}")
				rst.append("")
				if method["docstring"]:
					rst.append(f"      {escape_rst(method['docstring'])}")
					rst.append("")

		rst.append("")

	return "\n".join(rst) + "\n"


def main():
	"""Generate MCP server RST documentation."""
	repo_root = Path(__file__).parent.parent.parent
	mcp_dir = repo_root / "mcp-server"
	output_path = repo_root / "docs" / "sphinx" / "api" / "mcp_servers.rst"

	if not mcp_dir.exists():
		print(f"Error: {mcp_dir} not found")
		return

	rst_content = generate_rst(mcp_dir)

	with open(output_path, "w", encoding="utf-8") as f:
		f.write(rst_content)

	print(f"Generated {output_path}")
	print(f"  Servers documented: {sum(1 for f in mcp_dir.glob('*.py') if not f.name.startswith('test_'))}")


if __name__ == "__main__":
	main()
